// 错误码全表唯一来源（doc/detailed-design.md §6.5）
export const E = {
  INVALID_PARAMS: 'INVALID_PARAMS',
  AMOUNT_INVALID: 'AMOUNT_INVALID',
  BASE_CHIPS_INVALID: 'BASE_CHIPS_INVALID',
  NICKNAME_INVALID: 'NICKNAME_INVALID',
  TRANSFER_SELF: 'TRANSFER_SELF',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_INVALID: 'AUTH_INVALID',
  NOT_MEMBER: 'NOT_MEMBER',
  NOT_HOST: 'NOT_HOST',
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  ALREADY_IN_ROOM: 'ALREADY_IN_ROOM',
  NICKNAME_TAKEN: 'NICKNAME_TAKEN',
  ROOM_DISSOLVED: 'ROOM_DISSOLVED',
  BET_EXCEEDS_CHIPS: 'BET_EXCEEDS_CHIPS',
  POOL_EMPTY: 'POOL_EMPTY',
  PARTIAL_GE_POOL: 'PARTIAL_GE_POOL',
  REBUILD_CONFIRM_REQUIRED: 'REBUILD_CONFIRM_REQUIRED',
  TRANSFER_TARGET_INVALID: 'TRANSFER_TARGET_INVALID',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  GAME_NOT_ACTIVE: 'GAME_NOT_ACTIVE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};

const HTTP_BY_CODE = {
  [E.INVALID_PARAMS]: 400,
  [E.AMOUNT_INVALID]: 400,
  [E.BASE_CHIPS_INVALID]: 400,
  [E.NICKNAME_INVALID]: 400,
  [E.TRANSFER_SELF]: 400,
  [E.AUTH_REQUIRED]: 401,
  [E.AUTH_INVALID]: 401,
  [E.NOT_MEMBER]: 403,
  [E.NOT_HOST]: 403,
  [E.ROOM_NOT_FOUND]: 404,
  [E.ALREADY_IN_ROOM]: 409,
  [E.NICKNAME_TAKEN]: 409,
  [E.ROOM_DISSOLVED]: 409,
  [E.BET_EXCEEDS_CHIPS]: 409,
  [E.POOL_EMPTY]: 409,
  [E.PARTIAL_GE_POOL]: 409,
  [E.REBUILD_CONFIRM_REQUIRED]: 409,
  [E.TRANSFER_TARGET_INVALID]: 409,
  [E.IDEMPOTENCY_CONFLICT]: 409,
  [E.GAME_NOT_ACTIVE]: 409,
  [E.INTERNAL_ERROR]: 500,
};

export class AppError extends Error {
  constructor(code, message, details = undefined) {
    super(message || code);
    this.name = 'AppError';
    this.code = code;
    this.httpStatus = HTTP_BY_CODE[code] ?? 500;
    this.details = details;
  }
}
